### ISSUE TITLE
panic in node stop

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#1316]
```
Please note that if your node(s) are validating a Subnet, stopping them could cause Subnet instability and it is irreversible
✔ Yes
Stopping node instance i-07b7282973f652e6d in cluster cluster1...
Stopping node instance i-02182f6703337a96d in cluster cluster1...
Stopping node instance i-0ab27d8a872b98b68 in cluster cluster1...
Stopping node instance i-0123dc50eddc77cfa in cluster cluster1...
Stopping node instance i-03c47b2bc597422a2 in cluster cluster1...
Stopping node instance i-0bbbd2bb5e053086e in cluster cluster1...
Stopping node instance i-0aa1003bf29b75641 in cluster cluster1...
Stopping node instance i-02f7cdae67d6fbff1 in cluster cluster1...
Stopping node instance i-06ff813b332c684d3 in cluster cluster1...
Stopping node instance i-0be5f52c713cd36d7 in cluster cluster1...
Failed nodes: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2650834]

goroutine 1 [running]:
github.com/ava-labs/avalanche-cli/cmd/nodecmd.stopNodes(0xc000f2e900?, {0xc00131c4a0?, 0x1?, 0x1?})
	/home/fm/Workdir/projects/avalanche-cli/cmd/nodecmd/stop.go:159 +0xbb4
github.com/spf13/cobra.(*Command).execute(0xc000f2e900, {0xc00131c450, 0x1, 0x1})
	/home/fm/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0008d6f00)
	/home/fm/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/fm/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/ava-labs/avalanche-cli/cmd.Execute()
	/home/fm/Workdir/projects/avalanche-cli/cmd/root.go:313 +0x50
main.main()
	/home/fm/Workdir/projects/avalanche-cli/main.go:10 +0x17
exit status 2
```

**Comment by felipemadero** [comment]
Closed by https://github.com/ava-labs/avalanche-cli/pull/1314
